### PR TITLE
Fix bugs in shell script for bazelci

### PR DESCRIPTION
**Pull request by Quarz0**

### CODE REVIEW

**Comment by Quarz0** [comment]
I'm not sure why a build was not triggered on [buildkite](https://buildkite.com/bazel/starlark/builds) for this PR...

**Comment by laurentlb** [comment]
cc @fweikert - the build was not triggered?

**Comment by fweikert** [comment]
I changed the Buildkite config to also trigger builds for forked repos. If you push another commit to this PR, the tests should run.

**Comment by Quarz0** [comment]
@laurentlb - The build is passing now.

**Pull request merged**
