### PR TITLE
Generate spec.md table of contents

### PR DESCRIPTION
**Pull request by stepancheg**
It was out of sync, but it is correct now.

This diff includes:
* `spec_md_gen.py` script to regenerated `spec.md`
* `spec_md_gen_test.py` test which verifies `spec.md` TOC is in sync
* `spec.md` regenerated

### CODE REVIEW

**Review by laurentlb — COMMENTED** [review]
Nice!

Do you think we could do it with a single file (and the script would update it)?

I want to keep it simple to contribute changes to the spec. If I need to update two files (or install / run Bazel), that would be a bit of overhead, especially when my change doesn't affect the TOC.

**Comment by adonovan** [comment]
I wonder whether this is necessary. If you read Markdown in GitHub, as I suspect nearly all readers do, it already shows a table of contents. Also, browser search is probably good enough for the long list of built-in functions.

If we removed the built-in functions  from the ToC, would we still need a script to update it? It changes almost never.

**Comment by stepancheg** [comment]
I updated the PR to update `spec.md` in place.

> If we removed the built-in functions from the ToC

I think builtin functions in TOC are good to have.

I learned only today that github has TOC viewer, and I found it not very convenient to use.

But I'm fine with removing them.

> would we still need a script to update it? 

No we won't.

**Review by laurentlb — APPROVED** [review]
Thanks!

Since we have a manual TOC, I think the code is simple enough and provides enough value.

**Pull request merged**
