### PR TITLE
Add `Starlet` to the Users section in `users.md`

### PR DESCRIPTION
**Pull request by vt128**
This PR aims to add [*Starlet*](https://github.com/1set/starlet) to the list of Starlark users.

Starlet is a Go wrapper for the official [*Starlark in Go*](https://github.com/google/starlark-go) project, designed to enhance the Starlark scripting experience with powerful extensions and enriched wrappers. It offers an intuitive API for executing Starlark scripts, managing global variables, loading modules, controlling the script execution flow, and handling script outputs. Besides, it provides a simplified data exchange mechanism between Go and Starlark types.

Moreover, Starlet includes a set of custom modules and libraries that extend the functionality of the Starlark language, covering a wide range of use cases, such as file manipulation, HTTP client, JSON/CSV handling, and more.

The addition of Starlet to the list of Starlark users would provide a valuable resource for the community, as it illustrates a practical use of Starlark and offers a toolset that can simplify and enhance the Starlark scripting experience for developers.

Please let me know if there are any questions or if further information is needed.

Thanks!

### CODE REVIEW

**Comment by vt128** [comment]
@tetromino @stepancheg @laurentlb Could you please review this PR and consider merging it? Thanks!

**Review by laurentlb — APPROVED** [review]

**Comment by laurentlb** [comment]
I've found that I no longer have write access here. Sorry :(
https://github.com/bazelbuild/starlark/pull/269 has also been pending for a long time.

cc @meisterT

**Comment by vt128** [comment]
> I've found that I no longer have write access here. Sorry :( #269 has also been pending for a long time.
> 
> cc @meisterT

Ah, thanks for the update, @laurentlb! No worries, I appreciate you taking the time to review it. Let's hope the maintainers can address them soon.

**Review by tetromino — CHANGES_REQUESTED** [review]
The "users" section is supposed to be for projects that were created to *do some intrinsically useful, non-Starlark-related task* but happen to *use* Starlark as a scripting or config language.

Instead, we started putting things like skycfg, starlark-go-nethttp, starlight, and now starlet there; these are not users, these are libraries intended to be used by the users.

I would suggest adding a new "Libraries and extensions" section between tools and IDEs; and moving the skycfg, starlark-go-nethttp, starlight, and starlet items there.

**Comment by vt128** [comment]
@tetromino Sounds good, I've updated the PR as per your suggestion.

**Review by tetromino — APPROVED** [review]

**Comment by tetromino** [comment]
Thanks!

**Pull request merged**
