### PR TITLE
Update CODEOWNERS

### PR DESCRIPTION
**Pull request by brandjon**
Laurent, I assume you don't want to get emails for PRs in this repo?

If you do want to stay on, we should probably add Alan and myself as well to the file.

### CODE REVIEW

**Review by alandonovan — APPROVED** [review]

**Comment by laurentlb** [comment]
Dmitry wanted to have CODEOWNERS files in all bazelbuild/ repos, so that we know who's maintaining the repository.

I'm happy to continue maintaining this one, so we can have the 3 names here maybe?

**Comment by brandjon** [comment]
That's a reasonable philosophy, though it's annoying that github puts every codeowner on every PR. If you're happy to stay on as maintainer then we certainly won't remove you. Alan, shall it be the three of us in the file?

**Comment by jin** [comment]
Please don't remove CODEOWNERS: it helps the Bazel DevEx gardeners team understand who the right maintainers are for each repo.

**Comment by alandonovan** [comment]
Jon, will you revert this?

**Comment by brandjon** [comment]
Added ourselves to codeowners so it's not just Laurent.

**Review by alandonovan — APPROVED** [review]

**Pull request merged**
