### PR TITLE
Use main branch for starlark-rust repo

### PR DESCRIPTION
**Pull request by styurin**
https://github.com/facebookexperimental/starlark-rust/commits/main

### CODE REVIEW

**Comment by laurentlb** [comment]
ping @brandjon

**Comment by laurentlb** [comment]
I should be able to merge when the tests pass. We could comment out the tests that don't pass if needed.

**Comment by fmeum** [comment]
The remaining CI failures are all due to Rust Starlark and seem to be about error message patterns. However, `bazel test //...` passes on my local machine, including the tests that fail in the CI, which is very weird.

**Comment by fmeum** [comment]
@ndmitchell Do you happen to have an idea what's wrong with the tests? They pass locally (at least on my machine).

**Comment by laurentlb** [comment]
It's probably an old error - I've merged https://github.com/bazelbuild/starlark/pull/213 instead, as the tests were passing.

**Pull request closed without merging**
